variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

cache:
    paths:
        - node_modules/

# build:
#     image: node:latest
#     stage: build
#     tags:
#         - shared
#     script:
#         - npm install
#         - npm run build
#     artifacts:
#         paths:
#             - dist

deploy:
    image: docker/compose:latest
    environment:
        name: production
        url: https://bibites.kkhost.pl
    dependencies:
        - build
    tags:
        - shared
    script:
        - ls -la /var/run
        - docker-compose down
        - docker-compose build
        - docker-compose up
