variables:
    DOCKER_HOST: tcp://192.168.1.5:2375
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

cache:
    paths:
        - node_modules/

build:
    image: node:latest
    stage: build
    tags:
        - shared
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist

deploy:
    image: docker/compose:latest
    variables:
        GIT_STRATEGY: none
    environment:
        name: production
        url: https://bibites.kkhost.pl
    dependencies:
        - build
    tags:
        - shared
    script:
        - docker stop bibites
        - docker rm bibites
        - docker build . -t bibites
        - docker run -d bibites
