image: node:latest

cache:
    paths:
        - node_modules/

build:
    stage: build
    tags:
        - shared
    script:
        - npm install
        - npm run build

deploy:
    image: node:latest
    tags:
        - shared
    script:
        - npm run build
        - npm run serve
